---
- name: Verify cluster is initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeconfig_check
  tags: join

- name: Fail if cluster not ready
  ansible.builtin.fail:
    msg: "Cluster not initialized. Run init_cluster.yml first."
  when: not kubeconfig_check.stat.exists
  tags: join

- name: Get existing join tokens
  ansible.builtin.shell: |
    kubeadm token list | grep -P '\sjoin$' | awk '{print $1}' | head -1
  register: existing_token
  changed_when: false
  args:
    executable: /bin/bash
  when: kubeconfig_check.stat.exists
  tags: join

- name: Generate new join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  when: 
    - kubeconfig_check.stat.exists
    - existing_token.stdout == ""
  changed_when: "'kubeadm join' in join_command.stdout"
  tags: join

- name: Reuse existing token if valid
  ansible.builtin.set_fact:
    join_command: "{{ {'stdout': existing_token.stdout} }}"  # Приводим к тому же формату
  when:
    - kubeconfig_check.stat.exists
    - existing_token.stdout != ""
  tags: join

- name: Register persistent join command
  ansible.builtin.set_fact:
    cluster_join_command: "{{ join_command.stdout | trim }}"
    cacheable: yes
  when: 
    - kubeconfig_check.stat.exists
    - join_command.stdout is defined
  tags: join

- name: Validate join command format
  ansible.builtin.assert:
    that:
      - "'kubeadm join' in cluster_join_command"
      - "'--token' in cluster_join_command"
      - "'--discovery-token-ca-cert-hash' in cluster_join_command"
    fail_msg: "Invalid join command format: {{ cluster_join_command | default('NOT_GENERATED') }}"
  when: inventory_hostname in groups['k8s_master']
  tags: join