---
- name: Add GitLab Runner GPG key
  ansible.builtin.apt_key:
    url: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
    state: present
  tags:
    - gitlab_runner
    - repo

- name: Ensure GitLab Runner repository is added
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.gitlab.com/runner/gitlab-runner/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: "gitlab-runner"
  tags:
    - gitlab_runner
    - repo

- name: Install GitLab Runner package
  ansible.builtin.apt:
    name: gitlab-runner
    state: present
    update_cache: yes
  tags:
    - gitlab_runner
    - install

- name: Ensure GitLab Runner service is running
  ansible.builtin.systemd:
    name: gitlab-runner
    state: started
    enabled: yes
  tags:
    - gitlab_runner
    - service

# Прверки что все работает

- name: Check if GitLab Runner repository exists
  ansible.builtin.shell:
    cmd: grep -q "packages.gitlab.com/runner/gitlab-runner" /etc/apt/sources.list.d/gitlab-runner.list
  register: repo_check
  changed_when: false
  tags: 
    - gitlab_runner
    - verify

- name: Check GitLab Runner version
  ansible.builtin.command:
    cmd: gitlab-runner --version
  register: runner_version
  changed_when: false
  tags: 
    - gitlab_runner
    - verify

- name: Display results
  ansible.builtin.debug:
    msg: |
      Repository added: {{ repo_check.rc == 0 }}
      GitLab Runner version: {{ runner_version.stdout }}
  tags: 
    - gitlab_runner
    - verify    